import type { SurveySchema } from './types';

// --- shared option scales -------------------------------------------------
const scaleNeverAlways = [
  { value: 1, label: 'Никогда' },
  { value: 2, label: 'Редко' },
  { value: 3, label: 'Иногда' },
  { value: 4, label: 'Часто' },
  { value: 5, label: 'Всегда' },
];

const scaleFreq = [
  { value: 1, label: 'Очень редко' },
  { value: 2, label: 'Редко' },
  { value: 3, label: 'Иногда' },
  { value: 4, label: 'Часто' },
  { value: 5, label: 'Очень часто' },
];

// --- survey schema --------------------------------------------------------
export const surveySchema: SurveySchema = [
  /* --------------------------------------------------------------------- */
  {
    id: 'emotional',
    title: 'Эмоциональная сфера',
    questions: [
      {
        id: 'q1_1',
        type: 'radio',
        text: 'Как часто ребёнок радуется мелочам?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q1_2',
        type: 'radio',
        text: 'Как часто ребёнок смеётся?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q1_3',
        type: 'text',
        text: 'Опишите момент, когда ребёнок испытывал сильную радость',
        required: true,
        placeholder: 'Ваш ответ…',
      },
      {
        id: 'q1_4',
        type: 'radio',
        text: 'Как ребёнок реагирует на подарки?',
        required: true,
        options: [
          { value: 1, label: 'Совсем не радуется' },
          { value: 2, label: 'Слабо выражает радость' },
          { value: 3, label: 'Иногда радуется' },
          { value: 4, label: 'Часто радуется' },
          { value: 5, label: 'Очень радуется' },
        ],
      },
      {
        id: 'q1_5',
        type: 'radio',
        text: 'Проявляет ли ребёнок энтузиазм к новому?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q1_6',
        type: 'radio',
        text: 'Как ребёнок выражает радость при встрече близких?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q1_7',
        type: 'radio',
        text: 'Как часто ребёнок улыбается без причины?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q1_8',
        type: 'radio',
        text: 'Как ребёнок реагирует на похвалу?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q1_9',
        type: 'radio',
        text: 'Насколько долго ребёнок сохраняет хорошее настроение?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q1_10',
        type: 'radio',
        text: 'Делится ли ребёнок радостью с другими?',
        required: true,
        options: scaleNeverAlways,
      },
    ],
  },
  /* --------------------------------------------------------------------- */
  {
    id: 'behaviour',
    title: 'Поведение',
    questions: [
      {
        id: 'q2_1',
        type: 'radio',
        text: 'Как часто ребёнок капризничает?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q2_2',
        type: 'radio',
        text: 'Легко ли ребёнок злится?',
        required: true,
        options: scaleFreq,
      },
      {
        id: 'q2_3',
        type: 'radio',
        text: 'Склонен ли ребёнок к агрессии?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q2_4',
        type: 'text',
        text: 'Опишите конфликтную ситуацию с участием ребёнка',
        required: true,
        placeholder: 'Ваш ответ…',
      },
      {
        id: 'q2_5',
        type: 'radio',
        text: 'Как ребёнок ведёт себя в новых ситуациях?',
        required: true,
        options: [
          { value: 1, label: 'Испытывает страх' },
          { value: 2, label: 'Часто тревожится' },
          { value: 3, label: 'Иногда волнуется' },
          { value: 4, label: 'В целом спокойно' },
          { value: 5, label: 'Уверенно себя чувствует' },
        ],
      },
      {
        id: 'q2_6',
        type: 'radio',
        text: 'Сколько времени нужно ребёнку, чтобы успокоиться после стресса?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q2_7',
        type: 'radio',
        text: 'Как часто ребёнок проявляет терпение?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q2_8',
        type: 'radio',
        text: 'Насколько аккуратен ребёнок с вещами?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q2_9',
        type: 'radio',
        text: 'Как часто ребёнок слушается запреты?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q2_10',
        type: 'radio',
        text: 'Как ребёнок реагирует на проигрыш в игре?',
        required: true,
        options: scaleNeverAlways,
      },
    ],
  },
  /* --------------------------------------------------------------------- */
  {
    id: 'social',
    title: 'Социальные навыки',
    questions: [
      {
        id: 'q3_1',
        type: 'radio',
        text: 'Насколько охотно ребёнок играет с другими детьми?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q3_2',
        type: 'radio',
        text: 'Как ребёнок делится игрушками?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q3_3',
        type: 'radio',
        text: 'Как ребёнок реагирует на просьбы взрослых?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q3_4',
        type: 'radio',
        text: 'Как ребёнок выражает сочувствие?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q3_5',
        type: 'text',
        text: 'Опишите пример, когда ребёнок проявил заботу о ком-то',
        required: true,
        placeholder: 'Ваш ответ…',
      },
      {
        id: 'q3_6',
        type: 'radio',
        text: 'Как легко ребёнок заводит новых друзей?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q3_7',
        type: 'radio',
        text: 'Умеет ли ребёнок сотрудничать в групповой игре?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q3_8',
        type: 'radio',
        text: 'Насколько ребёнок соблюдает правила игры?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q3_9',
        type: 'radio',
        text: 'Как ребёнок реагирует на критику сверстников?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q3_10',
        type: 'radio',
        text: 'Делится ли ребёнок успехами с другими?',
        required: true,
        options: scaleNeverAlways,
      },
    ],
  },
  /* --------------------------------------------------------------------- */
  {
    id: 'adaptive',
    title: 'Адаптивные навыки',
    questions: [
      {
        id: 'q4_1',
        type: 'radio',
        text: 'Как ребёнок адаптируется к изменениям распорядка дня?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q4_2',
        type: 'radio',
        text: 'Насколько ребёнок самостоятельный в быту?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q4_3',
        type: 'radio',
        text: 'Как ребёнок управляет эмоциями в трудных ситуациях?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q4_4',
        type: 'radio',
        text: 'Как ребёнок справляется с новыми задачами?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q4_5',
        type: 'radio',
        text: 'Насколько организован ребёнок в повседневных делах?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q4_6',
        type: 'radio',
        text: 'Как ребёнок планирует своё время игры или учёбы?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q4_7',
        type: 'radio',
        text: 'Насколько ребёнок внимателен к деталям?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q4_8',
        type: 'radio',
        text: 'Как ребёнок реагирует на неожиданные ситуации?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q4_9',
        type: 'radio',
        text: 'Способен ли ребёнок завершать начатые дела?',
        required: true,
        options: scaleNeverAlways,
      },
      {
        id: 'q4_10',
        type: 'radio',
        text: 'Как ребёнок оценивает собственные успехи и ошибки?',
        required: true,
        options: scaleNeverAlways,
      },
    ],
  },
  /* --------------------------------------------------------------------- */
  {
    id: 'overall',
    title: 'Общее эмоциональное состояние',
    questions: [
      {
        id: 'emotionalState',
        type: 'text',
        text: 'Опишите текущее эмоциональное состояние ребёнка в целом',
        required: true,
        placeholder: 'Ваш ответ…',
      },
    ],
  },
] as const;
