import type { SurveySchema } from './types';

export const surveySchema: SurveySchema = [
  {
    id: 'emotions',
    title: 'Эмоциональное состояние',
    questions: [
      {
        id: 'emotion_1',
        type: 'radio',
        text: 'Как часто ребёнок радуется мелочам?',
        required: true,
        options: [
          { value: 1, label: 'Никогда' },
          { value: 2, label: 'Редко' },
          { value: 3, label: 'Иногда' },
          { value: 4, label: 'Часто' },
          { value: 5, label: 'Всегда' },
        ],
      },
      {
        id: 'emotion_2',
        type: 'radio',
        text: 'Как часто ребёнок смеётся?',
        required: true,
        options: [
          { value: 1, label: 'Никогда' },
          { value: 2, label: 'Редко' },
          { value: 3, label: 'Иногда' },
          { value: 4, label: 'Часто' },
          { value: 5, label: 'Всегда' },
        ],
      },
      {
        id: 'emotion_3',
        type: 'text',
        text: 'Опишите момент, когда ребёнок испытывал сильную радость',
        required: true,
        placeholder: 'Ваш ответ…',
      },
      {
        id: 'emotion_4',
        type: 'radio',
        text: 'Как ребёнок реагирует на подарки?',
        required: true,
        options: [
          { value: 1, label: 'Совсем не радуется' },
          { value: 2, label: 'Слабо выражает радость' },
          { value: 3, label: 'Иногда радуется' },
          { value: 4, label: 'Часто радуется' },
          { value: 5, label: 'Очень радуется' },
        ],
      },
      {
        id: 'emotion_5',
        type: 'radio',
        text: 'Проявляет ли ребёнок энтузиазм к новому?',
        required: true,
        options: [
          { value: 1, label: 'Никогда' },
          { value: 2, label: 'Редко' },
          { value: 3, label: 'Иногда' },
          { value: 4, label: 'Часто' },
          { value: 5, label: 'Всегда' },
        ],
      },
    ],
  },
  {
    id: 'behaviour',
    title: 'Поведение',
    questions: [
      {
        id: 'behaviour_1',
        type: 'radio',
        text: 'Как часто ребёнок капризничает?',
        required: true,
        options: [
          { value: 1, label: 'Никогда' },
          { value: 2, label: 'Редко' },
          { value: 3, label: 'Иногда' },
          { value: 4, label: 'Часто' },
          { value: 5, label: 'Всегда' },
        ],
      },
      {
        id: 'behaviour_2',
        type: 'radio',
        text: 'Легко ли ребёнок злится?',
        required: true,
        options: [
          { value: 1, label: 'Очень редко' },
          { value: 2, label: 'Редко' },
          { value: 3, label: 'Иногда' },
          { value: 4, label: 'Часто' },
          { value: 5, label: 'Очень часто' },
        ],
      },
      {
        id: 'behaviour_3',
        type: 'radio',
        text: 'Склонен ли ребёнок к агрессии?',
        required: true,
        options: [
          { value: 1, label: 'Совсем нет' },
          { value: 2, label: 'Редко' },
          { value: 3, label: 'Иногда' },
          { value: 4, label: 'Часто' },
          { value: 5, label: 'Очень часто' },
        ],
      },
      {
        id: 'behaviour_4',
        type: 'text',
        text: 'Опишите конфликтную ситуацию с участием ребёнка',
        required: true,
        placeholder: 'Ваш ответ…',
      },
      {
        id: 'behaviour_5',
        type: 'radio',
        text: 'Как ребёнок ведёт себя в новых ситуациях?',
        required: true,
        options: [
          { value: 1, label: 'Испытывает страх' },
          { value: 2, label: 'Часто тревожится' },
          { value: 3, label: 'Иногда волнуется' },
          { value: 4, label: 'В целом спокойно' },
          { value: 5, label: 'Уверенно себя чувствует' },
        ],
      },
    ],
  },
  {
    id: 'social',
    title: 'Социальные навыки',
    questions: [
      {
        id: 'social_1',
        type: 'radio',
        text: 'Насколько охотно ребёнок играет с другими детьми?',
        required: true,
        options: [
          { value: 1, label: 'Совсем не играет' },
          { value: 2, label: 'Редко' },
          { value: 3, label: 'Иногда' },
          { value: 4, label: 'Часто' },
          { value: 5, label: 'Очень охотно' },
        ],
      },
      {
        id: 'social_2',
        type: 'radio',
        text: 'Как ребёнок делится игрушками?',
        required: true,
        options: [
          { value: 1, label: 'Никогда' },
          { value: 2, label: 'Редко' },
          { value: 3, label: 'Иногда' },
          { value: 4, label: 'Часто' },
          { value: 5, label: 'С радостью делится' },
        ],
      },
      {
        id: 'social_3',
        type: 'radio',
        text: 'Как ребёнок реагирует на просьбы взрослых?',
        required: true,
        options: [
          { value: 1, label: 'Игнорирует' },
          { value: 2, label: 'Редко откликается' },
          { value: 3, label: 'Иногда откликается' },
          { value: 4, label: 'Часто откликается' },
          { value: 5, label: 'Всегда вежлив' },
        ],
      },
      {
        id: 'social_4',
        type: 'radio',
        text: 'Как ребёнок выражает сочувствие?',
        required: true,
        options: [
          { value: 1, label: 'Не выражает' },
          { value: 2, label: 'Редко' },
          { value: 3, label: 'Иногда' },
          { value: 4, label: 'Часто' },
          { value: 5, label: 'Всегда заботится' },
        ],
      },
      {
        id: 'social_5',
        type: 'text',
        text: 'Опишите пример, когда ребёнок проявил заботу о ком-то',
        required: true,
        placeholder: 'Ваш ответ…',
      },
    ],
  },
];
